### ISSUE TITLE
GeoJSON seen as just one object?

### ISSUE THREAD

**Issue by iamlukesky** [makinacorpus/Leaflet.LayerIndex#4]
I have a GeoJSON FeaturCollection with around 5000 LineStrings. I tried adding it per the example code in the readme:   

    L.Map.include(L.LayerIndexMixin);

    var map = L.map(...);
    ...
    var layer = L.GeoJSON(data).addTo(map);
    map.indexLayer(layer);

    // Search visible features for example
    map.on('moveend', function () {
        var shown = map.search(map.getBounds());
        console.log(shown.length + ' objects shown.');
    });

But the `console.log` only ever outputs 1.

Am I supposed to add each feature as its own layer? (as is done with the circle markers in the live demo)

**Comment by leplatrem** [comment]
Yes, exactly. The specified layer is indexed by its bounds. If you want
individual object you'll have to index each sub-layer...
Don't hesitate to contribute some improvements if you think we can do
better ;)
Thanks!
