### ISSUE TITLE
How to integrate leaflet.layerindex.js in my code.

### ISSUE THREAD

**Issue by Vinaymanohar** [makinacorpus/Leaflet.LayerIndex#9]
Dear Sir,

I have seen the demo of the code, which is exact code that i am looking for to integrate in my code,

[Upload.zip](https://github.com/makinacorpus/Leaflet.LayerIndex/files/1865697/Upload.zip)

Please help me, how can i integrate the leaflet.layerindex.js in my data.

**Comment by leplatrem** [comment]
The source code of the demo is available here: https://github.com/makinacorpus/Leaflet.LayerIndex/tree/gh-pages

Otherwise, if you need assistance with your project, don't hesitate to send an email to contact@makina-corpus.com :)

**Comment by Vinaymanohar** [comment]
Dear Sir,

Can you show me how to call GeoJSON file and count number of markers within
the extent.

In your example you have written FOR LOOP to generate random points.,

**Comment by leplatrem** [comment]
You're right, if you only look at the `index.html`, you'll only see the `for loop`, but if you look where the  `InfoControl` is, you'll find what you want, which is more or less what's mentioned in the README:

https://github.com/makinacorpus/Leaflet.LayerIndex/blob/7eab4353890985453481256f7eef27f01ee1c307/index.html#L65 

https://github.com/makinacorpus/Leaflet.LayerIndex/blob/5b6351376baf93cce472c05b517fbe3438e6a09f/infocontrol.js#L12
